name: Cuckoo-release-build
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build
      run: |
        mkdir build
        cp -r LICENSE README.md archive.php bangumi.php functions.php links.php page.php post.php screenshot.jpg index.php 404.php libs/ includes/ assets/ build
        cd build && zip -q -r Cuckoo.zip * && mv Cuckoo.zip ../ && cd -
    - name: Run test echo
      run: echo fromJSON(${{ github.api_url }}/repos/bhaoo/Cuckoo-Action-Test/releases)[0].upload_url
    - name: Update Files
      uses: WebFreak001/deploy-nightly@v1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: fromJSON("${{ github.api_url }}/repos/bhaoo/Cuckoo-Action-Test/releases")[0].upload_url
        release_id: fromJSON("${{ github.api_url }}/repos/bhaoo/Cuckoo-Action-Test/releases")[0].id
        asset_path: ./Cuckoo.zip
        asset_name: Cuckoo-${{ github.ref_name }}.zip
        asset_content_type: application/zip
        max_releases: 1
